### ISSUE TITLE
摄像头型号

### ISSUE THREAD

**Issue by yin-qiyu** [p513817/YOLOv5_JetsonNano#1]
你好 请问你在jetaon调用yolo的时候是用的csi摄像头还是usb摄像头呢
yolo好像并不支持直接对csi摄像头的调用
请问有什么解决办法嘛 谢谢

**Comment by p513817** [comment]
你好，如果都是使用 OpenCV 來開啟的話，可以考慮參考 [JetsonHacksNano](https://github.com/JetsonHacksNano)/[CSI-Camera](https://github.com/JetsonHacksNano/CSI-Camera)  使用 csi 攝影機的方式。

**Comment by yin-qiyu** [comment]
好的感谢你。
